### ISSUE TITLE
Add new Foundational Security Best Practice standard (FSBP) controls

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-aws-compliance#534]
**Is your feature request related to a problem? Please describe.**

[AWS Announcement](https://aws.amazon.com/about-aws/whats-new/2022/12/aws-security-hub-new-security-best-practice-controls/)  -  [Dec 22, 2022]

The 9 [FSBP controls](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html) launched are:

- [x] [Account.1] Security contact information should be provided for an AWS account
- [x] [APIGateway.8] Websocket and HTTP API Gateway routes should specify an authorization type ([active issue](https://github.com/turbot/steampipe-plugin-aws/issues/1539))
- [x] [APIGateway.9] Access Logging should be enabled for API Gateway V2 Stages ([active issue](https://github.com/turbot/steampipe-plugin-aws/issues/1538))
- [x] [CloudFront.12] CloudFront distributions should not point to non-existent S3 origins
- [x] [CodeBuild.3] CodeBuild S3 logs should be encrypted
- [ ] [EC2.25] EC2 launch templates should not assign public IPs to network interfaces ([active issue](https://github.com/turbot/steampipe-plugin-aws/issues/1537))
- [x] [SageMaker.2] SageMaker notebook instances should be launched in a custom VPC
- [x] [SageMaker.3] Users should not have root access to SageMaker notebook instances
- [x] [WAF.10] AWS WAFv2 web ACL should have at least one rule or rule group

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
